version: "3.8"
services:
    php:
        image: php:7.4-fpm-alpine
        volumes:
            - ./:/srv
            - vendor:/srv/vendor:ro
        working_dir: /srv
        environment:
            - DATABASE=/srv/database/app.sqlite
            # - APP_ENV=production
        ports:
            - "80:80"
        entrypoint: [ 'php', '-S', '0.0.0.0:80', '-t', 'public/' ]
    migrate:
        image: php:7.4-fpm-alpine
        volumes:
            - ./:/srv
            - vendor:/srv/vendor:ro
        working_dir: /srv
        environment:
            - DATABASE=/srv/database/app.sqlite
        entrypoint: [ 'php', 'command', 'DatabaseMigrate' ]
        depends_on:
            - composer
    composer:
        image: composer:latest
        volumes:
            - ./:/srv
            - vendor:/srv/vendor
            - ${HOME}/.composer:/tmp
        working_dir: /srv
        command: install --ignore-platform-reqs
        depends_on:
            - php
volumes:
    vendor:
